version: '3.8'
services:
  storybook:
    container_name: storybook
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:80' # Map container's port 80 to host's port 6006
